<?php

return array (
  'version' => '6.2.2',
  'title' => '',
  'type' => 'team',
  'id' => '64b3a837c4045',
  'updated' => 1689497707,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Name',
      'width' => '200',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '64b3aaaf24dd30' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '80',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3aaaf24dd30',
    ),
    '64b3b05fa56040' => 
    array (
      'type' => 'field_5ea8308383966',
      'label' => 'Pronouns',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3b05fa56040',
    ),
    '64b3a7fbee5604' => 
    array (
      'type' => 'field_5ea830bb83968',
      'label' => 'Primary Title',
      'width' => '175',
      'width_unit' => 'px',
      'character_limit' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3a7fbee5604',
    ),
    '64b3abeefced90' => 
    array (
      'type' => 'field_64aee3c99cad2',
      'label' => 'Affiliations',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3abeefced90',
    ),
    '64b3ac82b74bc8' => 
    array (
      'type' => 'field_64aee4049cad4',
      'label' => 'Degrees',
      'width' => '180',
      'width_unit' => 'px',
      'character_limit' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3ac82b74bc8',
    ),
    '64b3ab1510a3d8' => 
    array (
      'type' => 'field_6209c8d1ff627',
      'label' => 'Email',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3ab1510a3d8',
    ),
    '64b3ab20ad9168' => 
    array (
      'type' => 'field_6209c8beff626',
      'label' => 'Phone',
      'width' => '125',
      'width_unit' => 'px',
      'character_limit' => '20',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3ab20ad9168',
    ),
    '64b3ab417ae148' => 
    array (
      'type' => 'field_64aee3e39cad3',
      'label' => 'Office/Room',
      'width' => '120',
      'width_unit' => 'px',
      'character_limit' => '20',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3ab417ae148',
    ),
    '64b3a82b2e147c' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Role',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'team_roles',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'separator' => 'comma',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3a82b2e147c',
    ),
    '64b3acebb0a3d8' => 
    array (
      'type' => 'field_64aee4129cad5',
      'label' => 'CV',
      'width' => '180',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3acebb0a3d8',
    ),
    '64b3aa8457ced8' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '200',
      'width_unit' => 'px',
      'date_format' => 'F j, Y g:i a',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '64b3aa8457ced8',
    ),
    '64b3afda7020c4' => 
    array (
      'type' => 'column-last_modified_author',
      'label' => 'By',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'on',
      'sort' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3afda7020c4',
    ),
  ),
  'settings' => 
  array (
    'roles' => 
    array (
    ),
    'users' => 
    array (
    ),
    'sorting' => '0',
    'sorting_order' => 'asc',
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'on',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'primary_column' => '',
    'filter_segment' => '',
  ),
);