<?php

return array (
  'version' => '6.2.2',
  'title' => '',
  'type' => 'post',
  'id' => '64b3b433db700',
  'updated' => 1689501185,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '500',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '64b3b4289c6a80' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '80',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3b4289c6a80',
    ),
    '64b3b9f3e9374c' => 
    array (
      'type' => 'column-excerpt',
      'label' => 'Excerpt',
      'width' => '400',
      'width_unit' => 'px',
      'excerpt_length' => '36',
      'before' => '',
      'after' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3b9f3e9374c',
    ),
    '64b3b9a868f5c4' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Feed',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'category',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'separator' => 'comma',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3b9a868f5c4',
    ),
    '64b3bdb63374bc' => 
    array (
      'type' => 'field_64b3bb264151a',
      'label' => 'Affiliated People',
      'width' => '250',
      'width_unit' => 'px',
      'post_property_display' => 'title',
      'character_limit' => '30',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'separator' => 'comma',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3bdb63374bc',
    ),
    '64b3b621a08314' => 
    array (
      'type' => 'column-sticky',
      'label' => 'Sticky',
      'width' => '85',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3b621a08314',
    ),
    'author' => 
    array (
      'type' => 'author',
      'label' => 'Author',
      'width' => '180',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'author',
    ),
    '64b3b56ba624dc' => 
    array (
      'type' => 'column-date_published',
      'label' => 'Published',
      'width' => '160',
      'width_unit' => 'px',
      'date_format' => 'wp_default',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '64b3b56ba624dc',
    ),
    '64b3b4999f3b64' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '200',
      'width_unit' => 'px',
      'date_format' => 'F j, Y g:i a',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '64b3b4999f3b64',
    ),
    '64b3b4a39ae148' => 
    array (
      'type' => 'column-last_modified_author',
      'label' => 'By',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'on',
      'sort' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b3b4a39ae148',
    ),
  ),
  'settings' => 
  array (
    'roles' => 
    array (
    ),
    'users' => 
    array (
    ),
    'sorting' => '0',
    'sorting_order' => 'asc',
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'on',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_filter_category' => 'off',
    'hide_filter_post_format' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'primary_column' => '',
    'filter_segment' => '',
  ),
);