<?php

return array (
  'version' => '6.2.2',
  'title' => '',
  'type' => 'project',
  'id' => '64b63e97e79cd',
  'updated' => 1689665632,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '415',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '64b63e6b126e98' => 
    array (
      'type' => 'field_64b63a687641b',
      'label' => 'Funding',
      'width' => '',
      'width_unit' => '%',
      'excerpt_length' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b63e6b126e98',
    ),
    '64b63eaaa45a1c' => 
    array (
      'type' => 'field_64b63a687642c',
      'label' => 'Date',
      'width' => '150',
      'width_unit' => 'px',
      'character_limit' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b63eaaa45a1c',
    ),
    '64b63f772978d4' => 
    array (
      'type' => 'field_64b63a6876410',
      'label' => 'Principal Investigator(s)',
      'width' => '180',
      'width_unit' => 'px',
      'post_property_display' => 'title',
      'character_limit' => '30',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'separator' => 'comma',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b63f772978d4',
    ),
    '64b63f88ab020c' => 
    array (
      'type' => 'field_64b63b6239053',
      'label' => 'Co-Investigator(s)',
      'width' => '180',
      'width_unit' => 'px',
      'post_property_display' => 'title',
      'character_limit' => '30',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'separator' => 'comma',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b63f88ab020c',
    ),
    '64b63f94da5e34' => 
    array (
      'type' => 'field_64b63b8a39054',
      'label' => 'Other Investigator(s)',
      'width' => '180',
      'width_unit' => 'px',
      'post_property_display' => 'title',
      'character_limit' => '30',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'separator' => 'comma',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b63f94da5e34',
    ),
    '64b63f9fcc49bc' => 
    array (
      'type' => 'field_64b63a6876444',
      'label' => 'Other Names',
      'width' => '',
      'width_unit' => '%',
      'excerpt_length' => '20',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b63f9fcc49bc',
    ),
    '64b63e896e5604' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'F j, Y g:i a',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '64b63e896e5604',
    ),
    '64b63e8f50e560' => 
    array (
      'type' => 'column-last_modified_author',
      'label' => 'By',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'on',
      'sort' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64b63e8f50e560',
    ),
  ),
  'settings' => 
  array (
    'roles' => 
    array (
    ),
    'users' => 
    array (
    ),
    'sorting' => '0',
    'sorting_order' => 'asc',
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'on',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'primary_column' => '',
    'filter_segment' => '',
  ),
);