<?php

return array (
  'version' => '6.2.2',
  'title' => '',
  'type' => 'page',
  'id' => '64c391b120f86',
  'updated' => 1691517130,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '64d280bd56c8b4' => 
    array (
      'type' => 'column-slug',
      'label' => 'Slug',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'search' => 'on',
      'name' => '64d280bd56c8b4',
    ),
    '64c3b324d0624c' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Featured Image',
      'width' => '',
      'width_unit' => '%',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64c3b324d0624c',
    ),
    '64c391abb81064' => 
    array (
      'type' => 'column-parent',
      'label' => 'Parent',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64c391abb81064',
    ),
    '64c3ad77c45a1c' => 
    array (
      'type' => 'column-page_template',
      'label' => 'Page Template',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64c3ad77c45a1c',
    ),
    '64c3f9f46bc6a8' => 
    array (
      'type' => 'column-permalink',
      'label' => 'Permalink',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'name' => '64c3f9f46bc6a8',
    ),
    '64c3add6e39580' => 
    array (
      'type' => 'column-meta',
      'label' => 'Sidebar Nav',
      'width' => '',
      'width_unit' => '%',
      'field' => 'sidebar_nav_menu',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'off',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64c3add6e39580',
    ),
    'author' => 
    array (
      'type' => 'author',
      'label' => 'Author',
      'width' => '10',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'author',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
  ),
  'settings' => 
  array (
    'roles' => 
    array (
    ),
    'users' => 
    array (
    ),
    'sorting' => '0',
    'sorting_order' => 'asc',
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'on',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'primary_column' => '',
    'filter_segment' => '',
  ),
);